name: Deploy Static Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Deploy Static site
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install Project Dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build
          ls -la

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ${{ github.workspace }}/public